-------PHANCONG
create or replace VIEW ADMIN.UV_GV_Phancong 
AS
    SELECT *
    FROM ADMIN.PHANCONG PC
    WHERE PC.MAGV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
create or replace VIEW ADMIN.UV_Quanly_Phancong 
AS
   SELECT PC.MAGV, pc.mahp, pc.hk, pc.nam, pc.mact
        FROM ADMIN.PHANCONG PC, ADMIN.HOCPHAN HP
    WHERE PC.MAHP = HP.MAHP AND HP.MADV = 'VPK';
/

CREATE OR REPLACE VIEW ADMIN.UV_TRGDV_QUANLY_PHANCONG
AS
    SELECT PC.MAGV,DV.MADV, HP.MAHP, PC.HK, PC.NAM, PC.MACT
    FROM ADMIN.PHANCONG PC JOIN ADMIN.HOCPHAN HP ON HP.MAHP= PC.MAHP
     JOIN ADMIN.DONVI DV ON DV.MADV = HP.MADV
    WHERE DV.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE TRIGGER ADMIN.UV_TRGDV_QUANLY_PHANCONG_INSERT
INSTEAD OF INSERT ON ADMIN.UV_TRGDV_QUANLY_PHANCONG
FOR EACH ROW
BEGIN
    INSERT INTO ADMIN.PHANCONG (MAGV, MAHP, HK, NAM, MACT)
    VALUES (:NEW.MAGV, :NEW.MAHP, :NEW.HK, :NEW.NAM, :NEW.MACT);
END;
/
CREATE OR REPLACE TRIGGER ADMIN.UV_TRGDV_QUANLY_PHANCONG_UPDATE
INSTEAD OF UPDATE ON ADMIN.UV_TRGDV_QUANLY_PHANCONG
FOR EACH ROW
BEGIN
    UPDATE ADMIN.PHANCONG
    SET MAGV = :NEW.MAGV,
        MAHP = :NEW.MAHP,
        HK = :NEW.HK,
        NAM = :NEW.NAM,
        MACT = :NEW.MACT
    WHERE MAGV = :OLD.MAGV
      AND MAHP = :OLD.MAHP
      AND HK = :OLD.HK
      AND NAM = :OLD.NAM
      AND MACT = :OLD.MACT;

END;
/
CREATE OR REPLACE TRIGGER ADMIN.UV_TRGDV_QUANLY_PHANCONG_DELETE
INSTEAD OF DELETE ON ADMIN.UV_TRGDV_QUANLY_PHANCONG
FOR EACH ROW
BEGIN
    DELETE FROM ADMIN.PHANCONG
    WHERE MAGV = :OLD.MAGV
      AND MAHP = :OLD.MAHP
      AND HK = :OLD.HK
      AND NAM = :OLD.NAM
      AND MACT = :OLD.MACT;

END;
/

CREATE OR REPLACE VIEW ADMIN.UV_TRGDV_PHANCONG
AS
    SELECT gv.manv, pc.hk, pc.nam, pc.mahp, pc.mact
    FROM ADMIN.NHANSU GV JOIN ADMIN.DONVI DV ON dv.madv = gv.madv 
        JOIN ADMIN.PHANCONG PC ON gv.manv =pc.magv
    WHERE DV.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER');

/

CREATE OR REPLACE PROCEDURE ADMIN.GET_UV_TRGDV_PHANCONG2 (
    p_username IN VARCHAR2,
    p_result OUT SYS_REFCURSOR
) AS
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=true';
        EXECUTE IMMEDIATE 'REVOKE RL_TRUONGBM FROM ' || p_username;
        EXECUTE IMMEDIATE 'GRANT RL_TRUONGKHOA TO ' || p_username;

        OPEN p_result FOR
        SELECT gv.manv, pc.hk, pc.nam, pc.mahp, pc.mact
        FROM ADMIN.NHANSU GV 
        JOIN ADMIN.DONVI DV ON dv.madv = gv.madv 
        JOIN ADMIN.PHANCONG PC ON gv.manv = pc.magv
        WHERE DV.TRGDV = SYS_CONTEXT('USERENV', 'SESSION_USER');

        EXECUTE IMMEDIATE 'REVOKE RL_TRUONGKHOA FROM ' || p_username;
        EXECUTE IMMEDIATE 'GRANT RL_TRUONGBM TO ' || p_username;
    EXCEPTION
        WHEN OTHERS THEN
            EXECUTE IMMEDIATE 'REVOKE RL_TRUONGKHOA FROM ' || p_username;
            EXECUTE IMMEDIATE 'GRANT RL_TRUONGBM TO ' || p_username;
            EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=false';
            RAISE;
    END;
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=false';
END;
/

GRANT EXECUTE ON ADMIN.GET_UV_TRGDV_PHANCONG TO RL_TRUONGBM;

GRANT EXECUTE ON ADMIN.GET_UV_TRGDV_PHANCONG TO RL_TRUONGBM;
GRANT SELECT ON ADMIN.UV_GV_Phancong  TO RL_GIANGVIEN;
/
GRANT SELECT, UPDATE ON ADMIN.UV_Quanly_Phancong TO RL_GIAOVU;
GRANT SELECT, UPDATE ON ADMIN.UV_Quanly_Phancong TO RL_GIAOVU;
/ 
GRANT SELECT ON ADMIN.PHANCONG TO RL_GIAOVU;

/
GRANT SELECT, UPDATE, DELETE, INSERT ON ADMIN.UV_TRGDV_QUANLY_PHANCONG TO RL_TRUONGBM;
GRANT SELECT ON ADMIN.UV_TRGDV_PHANCONG TO RL_TRUONGBM;


----PHANCONG (TruongKhoa)
create or replace view TRK_PHANCONG_VIEW 
as
select * from PHANCONG
where MAHP in (select MAHP from HOCPHAN where MADV = 'VPK');


grant select on TRK_PHANCONG_VIEW to RL_TRUONGKHOA;
grant insert on TRK_PHANCONG_VIEW to RL_TRUONGKHOA;
grant update on TRK_PHANCONG_VIEW to RL_TRUONGKHOA;
grant delete on TRK_PHANCONG_VIEW to RL_TRUONGKHOA;

