SELECT VALUE FROM v$option WHERE parameter = 'Oracle Label Security'; 
SELECT status FROM dba_ols_status WHERE name = 'OLS_CONFIGURE_STATUS';
EXEC LBACSYS.CONFIGURE_OLS;
EXEC LBACSYS.OLS_ENFORCEMENT.ENABLE_OLS; 
SHUTDOWN IMMEDIATE; 
STARTUP; 
SELECT * FROM DBA_OLS_STATUS;
select * from v$services; 
ALTER USER lbacsys IDENTIFIED BY lbacsys ACCOUNT UNLOCK; 
ALTER PLUGGABLE DATABASE OLS_DEMO OPEN READ WRITE; 
SHOW CON_NAME; 

CREATE USER ADMIN_OLS IDENTIFIED BY ADMIN123 CONTAINER = CURRENT; 
GRANT CONNECT,RESOURCE TO ADMIN_OLS; --C?P QUY?N CONNECT VÀ RESOURCE 
GRANT UNLIMITED TABLESPACE TO ADMIN_OLS; --C?P QUOTA CHO ADMIN_OLS 
GRANT SELECT ANY DICTIONARY TO ADMIN_OLS; --C?P QUY?N ??C DICTIONARY
SELECT * FROM ALL_USERS;
GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_user_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.sa_label_admin TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON sa_policy_admin TO ADMIN_OLS WITH GRANT OPTION;
GRANT EXECUTE ON char_to_label TO ADMIN_OLS WITH GRANT OPTION; 
GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO ADMIN_OLS;
GRANT EXECUTE ON LBACSYS.SA_AUDIT_ADMIN TO ADMIN_OLS;

GRANT LBAC_DBA TO ADMIN_OLS; 
GRANT EXECUTE ON sa_sysdba TO ADMIN_OLS;  
GRANT EXECUTE ON TO_LBAC_DATA_LABEL TO ADMIN_OLS; -- C?P QUY?N TH?C THI
GRANT INHERIT PRIVILEGES ON USER ADMIN_OLS TO lbacsys;
-- DROP POLICY
BEGIN
    SA_SYSDBA.DROP_POLICY(
        policy_name => 'OLS_THONGBAO'
    );
END;
/

BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name => 'OLS_THONGBAO', 
    column_name => 'OLS_LABEL'
  );
END;
/
GRANT OLS_THONGBAO_DBA TO ADMIN_OLS;
set role all;

EXEC SA_SYSDBA.ENABLE_POLICY ('OLS_THONGBAO'); 
SHUTDOWN IMMEDIATE; 
STARTUP; 
-- CREATE LEVEL, COMPARTMENT, GROUP
BEGIN
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 600,
        short_name   => 'TK',
        long_name    => 'Truong Khoa'
    );
    
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 500,
        short_name   => 'TBM',
        long_name    => 'Truong Bo Mon'
    );
    
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 400,
        short_name   => 'GV',
        long_name    => 'Giang Vien'  
    );
    
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 300,
        short_name   => 'GVU',
        long_name    => 'Giao Vu'  
    );
    
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 200,
        short_name   => 'NV',
        long_name    => 'Nhan Vien'  
    );
    
    SA_COMPONENTS.CREATE_LEVEL(
        policy_name  => 'OLS_THONGBAO',
        level_num    => 100,
        short_name   => 'SV',
        long_name    => 'Sinh Vien'  
    );
END;
/


BEGIN
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 200,
        short_name   => 'HTTT',
        long_name    => 'He thong thong tin' 
    );
    
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 180,
        short_name   => 'CNPM',
        long_name    => 'Cong nghe phan mem'
    );
    
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 160,
        short_name   => 'KHMT',
        long_name    => 'Khoa hoc may tinh'
    );
    
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 140,
        short_name   => 'CNTT',
        long_name    => 'Cong nghe thong tin' 
    );
    
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 120,
        short_name   => 'TGMT',
        long_name    => 'Thi giac may tinh'
    );
    
    SA_COMPONENTS.CREATE_COMPARTMENT(
        policy_name  => 'OLS_THONGBAO',
        comp_num     => 100,
        short_name   => 'MMT',
        long_name    => 'Mang may tinh'
    );
END;
/
BEGIN
    SA_COMPONENTS.CREATE_GROUP(
        policy_name  => 'OLS_THONGBAO',
        group_num     => 40,
        short_name   => 'CS1',
        long_name    => 'Co So 1'
    );
    
    SA_COMPONENTS.CREATE_GROUP(
        policy_name  => 'OLS_THONGBAO',
        group_num     => 20,
        short_name   => 'CS2',
        long_name    => 'Co So 2'
    );
END;
/
SELECT * FROM DBA_OLS_STATUS;
SELECT * FROM DBA_SA_LEVELS; 
SELECT * FROM DBA_SA_COMPARTMENTS; 
SELECT * FROM DBA_SA_GROUPS; 
SELECT * FROM DBA_SA_GROUP_HIERARCHY;

DROP TABLE ADMIN_OLS.THONGBAO;

CREATE TABLE ADMIN_OLS.THONGBAO (
    ID INT,
    NoiDung NVARCHAR2(500),
    PRIMARY KEY (ID)
);

-- INSERT 
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (1, N'Thông báo cho Truong Khoa.');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (2, N'Thông báo cho Truong bo mon');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (3, N'Thông báo cho Giang Vien.');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (4, N'Thông báo cho Giao Vu.');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (5, N'Thông báo cho nhan vien.');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (6, N'Thông báo SV HTTT');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (7, N'Thông báo TBM HTTT CS1');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (8, N'Thông báo SV CNPM.');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (9, N'Thông báo SV KHMT');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (10, N'Thông báo SV CNTT');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (11, N'Thông báo SV TGMT');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (12, N'Thông báo SV MMT');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (13, N'Thông báo cho SV CS1');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (14, N'Thông báo cho SV CS2');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (15, N'Thông báo cho SV HTTT CS1');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (16, N'Thông báo cho TBM KHMT CS2');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (17, N'Thông báo cho GV CNPM');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (18, N'Thông báo cho GV KHMT CS1');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (19, N'Thông báo cho TBM CNTT CS2');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (20, N'Thông báo cho GVU CS2');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (21, N'Thông báo cho GVU');

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (22, N'Thông báo cho GVU CS1');
COMMIT;

EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1990, 'TK'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1980, 'TBM'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1970, 'GV'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1960, 'GVU'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1950, 'NV'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1940, 'SV:HTTT'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1930, 'TBM:HTTT:CS1'); 
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1920, 'SV:CNPM');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1910, 'SV:KHMT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1900, 'SV:CNTT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1890, 'SV:TGMT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1880, 'SV:MMT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1870, 'SV::CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1860, 'SV::CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1850, 'SV:HTTT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1840, 'TBM:KHMT:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1830, 'GV:CNPM');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1820, 'GV:KHMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1810, 'TBM:CNTT:CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1800, 'GVU::CS2');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1780, 'GVU::CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1770, 'TBM:KHMT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1760, 'TBM:KHMT');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1750, 'GV:KHMT,HTTT:CS1');
EXECUTE SA_LABEL_ADMIN.CREATE_LABEL('OLS_THONGBAO', 1740, 'SV:KHMT:CS1');
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY(
    POLICY_NAME  => 'OLS_THONGBAO',
    SCHEMA_NAME  => 'ADMIN_OLS',
    TABLE_NAME  => 'THONGBAO',
    TABLE_OPTIONS => 'NO_CONTROL'
);
END;
/



SELECT * FROM ADMIN_OLS.THONGBAO;

UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TK') WHERE ID = 1;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM') WHERE ID = 2;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GV') WHERE ID = 3;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GVU') WHERE ID = 4;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'NV') WHERE ID = 5;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:HTTT') WHERE ID = 6;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM:HTTT:CS1') WHERE ID = 7;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:CNPM') WHERE ID = 8;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:KHMT') WHERE ID = 9;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:CNTT') WHERE ID = 10;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:TGMT') WHERE ID = 11;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:MMT') WHERE ID = 12;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV::CS1') WHERE ID = 13;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV::CS2') WHERE ID = 14;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:HTTT:CS1') WHERE ID = 15;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM:KHMT:CS2') WHERE ID = 16;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GV:CNPM') WHERE ID = 17;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GV:KHMT:CS1') WHERE ID = 18;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM:CNTT:CS2') WHERE ID = 19;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GVU::CS2') WHERE ID = 20;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GVU') WHERE ID = 21;
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GVU::CS1') WHERE ID = 22;

BEGIN
SA_POLICY_ADMIN.REMOVE_TABLE_POLICY(
policy_name => 'OLS_THONGBAO',
schema_name => 'ADMIN_OLS',
table_name  => 'THONGBAO'
);
END;
/
BEGIN
SA_POLICY_ADMIN.APPLY_TABLE_POLICY (
policy_name => 'OLS_THONGBAO',
schema_name => 'ADMIN_OLS',
table_name => 'THONGBAO',
table_options => 'READ_CONTROL',
predicate => NULL
);
END;
/
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE
CREATE USER TK001 IDENTIFIED BY TK001;
CREATE USER TBMCS2 IDENTIFIED BY TBMCS2;
CREATE USER GVU001 IDENTIFIED BY GVU001;
CREATE USER SVHTTT IDENTIFIED BY SVHTTT;
--CREATE USER NVCB IDENTIFIED BY NVCB;
--CREATE USER GVKHMT IDENTIFIED BY GVKHMT;
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TK001, TBMCS2, SVHTTT, GVU001;

--Cau a: TRUONGKHOA CO THE DOC DUOC TOAN BO BANG
BEGIN    
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'OLS_THONGBAO',
        USER_NAME    => 'TK001',
        MAX_READ_LABEL => 'TK:HTTT,KHMT,CNPM,MMT,TGMT,CNTT:CS1,CS2',
        MAX_WRITE_LABEL => 'TK:HTTT,KHMT,CNPM,MMT,TGMT,CNTT:CS1,CS2'
    );
END;
/

--Cau b:  TRUONGBM PHU TRACH CS2 CO THE DOC DUOC TOAN BO
-- THONG BAO DANH CHO TRUONG BO MON KHONG PHAN BIET VI TRI DIA LY
BEGIN    
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'OLS_THONGBAO',
        USER_NAME    => 'TBMCS2',
        MAX_READ_LABEL => 'TBM:HTTT,KHMT,CNPM,MMT,TGMT,CNTT:CS1,CS2',
        MAX_WRITE_LABEL => 'TBM:HTTT,KHMT,CNPM,MMT,TGMT,CNTT:CS1,CS2'
    );
END;
/

-- c) GIAO VU CO THE DOC TOAN BO THONG BAO DANH CHO GIAO VU
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'OLS_THONGBAO',
        USER_NAME    => 'GVU001',
        MAX_READ_LABEL => 'GVU::CS1,CS2',
        MAX_WRITE_LABEL => 'GVU::CS1,CS2'
    );
END;
/

-- d) 
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (23, N'Thông báo t1 cho Truong don vi.');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM') WHERE ID = 23;
-- e)
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (24, N'Thông báo t2 cho Sinh viên HTTT h?c ? C? s? 1.');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:HTTT:CS1') WHERE ID = 24;
-- f)
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (25, N'Thông báo t3 cho Tr??ng b? môn KHMT ? C? s? 1');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM:KHMT:CS1') WHERE ID = 25;
-- g)
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (26, N'Thông báo t4 cho Tr??ng b? môn KHMT ? C? s? 1 và C? s? 2.');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'TBM:KHMT') WHERE ID = 26;
-- h)
INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (27, N'Thông báo t5 cho Nhân viên ? C? s? 1 và C? s? 2.');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'NV') WHERE ID = 27;

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (28, N'Thông báo t6 cho gi?ng viên HTTT CS1');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'GV:HTTT:CS1') WHERE ID = 28;

INSERT INTO ADMIN_OLS.THONGBAO (ID, NoiDung)
VALUES (29, N'Thông báo t7 cho Sinh viên KHMT CS1');
UPDATE ADMIN_OLS.THONGBAO SET OLS_LABEL = CHAR_TO_LABEL('OLS_THONGBAO', 'SV:KHMT:CS1') WHERE ID = 29;
BEGIN
    SA_USER_ADMIN.SET_USER_LABELS(
        POLICY_NAME  => 'OLS_THONGBAO',
        USER_NAME    => 'SVHTTT',
        MAX_READ_LABEL => 'SV:HTTT:CS1',
        MAX_WRITE_LABEL => 'SV:HTTT:CS1'
    );
END;
/

SELECT * FROM ALL_SA_USER_LABELS; -- XEM TAT CA LABEL DUOC GAN CHO USER
SELECT * FROM ALL_SA_LABELS; -- XEM TAT CA LABEL TRONG DATABASE
GRANT SELECT ON ADMIN_OLS.THONGBAO TO TBMCS2;
SELECT * FROM ALL_USERS;
SHOW CON_NAME;
