CREATE OR REPLACE PROCEDURE ADMIN.UPDATE_STUDENT (DCHI NVARCHAR2, DT NVARCHAR2)
AS
    STRSQL VARCHAR(2000);
BEGIN
    IF DCHI IS NULL OR DCHI = '' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Thông tin địa chỉ không được để trống');
    END IF;
    IF DT IS NULL OR DT = '' THEN
        RAISE_APPLICATION_ERROR(-20002, 'Thông tin số điện thoại không được để trống');
    END IF;
    STRSQL := 'UPDATE ADMIN.SINHVIEN SET DCHI = '''|| DCHI || '''';
    EXECUTE IMMEDIATE (STRSQL);
    STRSQL := 'UPDATE ADMIN.SINHVIEN SET DT = '''|| DT || '''';
    EXECUTE IMMEDIATE (STRSQL);
END;
/
GRANT EXECUTE ON ADMIN.UPDATE_STUDENT TO SINHVIEN;