CREATE OR REPLACE PROCEDURE GetUsersOfRole(Role_name IN VARCHAR2, UsersCursor OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN UsersCursor FOR
    SELECT GRANTEE
    FROM DBA_ROLE_PRIVS
    WHERE GRANTED_ROLE = Role_name;
END;