create or replace view NHANSU_VIEW AS
SELECT MANV, HOTEN, PHAI, NGSINH
FROM NHANSU 
WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');

create or replace view SINHVIEN_VIEW AS
SELECT MASV, HOTEN, PHAI, NGSINH
FROM SINHVIEN
WHERE MASV = SYS_CONTEXT('USERENV', 'SESSION_USER');

create or replace view DONVI_VIEW AS
SELECT TENDV, TRGDV
FROM DONVI 
WHERE MADV = SYS_CONTEXT('USERENV', 'SESSION_USER');